### ISSUE TITLE
TYPO3 Extension

### ISSUE THREAD

**Issue by alexgunkel** [axel-kummer/logbook-php#1]
We need a TPO3-extension that makes using LogBook with TYPO3 really easy and that is hosted on TER.

**Comment by aseemann** [comment]
Hi @alexgunkel, 

I've crated a new repository for the TYPO3 Extension https://github.com/axel-kummer/t3x-aku_logbook

It's already published to packageist. Publishing in TER will take a while due to the account have to be checked manually ba the TYPO3.org team.

**Comment by aseemann** [comment]
(/) done
